Algoritmo "Exercicio9"
// Desenvolver um programa que apresente no final a
//soma dos valores pares existentes na faixa de 0 até 500.
//Utilize um laço que varie de 2 em 2.


var

contador, acumulador: inteiro



Inicio

contador <- 2
acumulador <- 0
  repita
   acumulador <- acumulador + contador
   contador <- contador + 2


  ate ( contador > 500 )
escreval ( acumulador)

Fimalgoritmo




Fimalgoritmo
