Algoritmo "questao7"
//Desenvolver um programa que apresente o valor de
//uma potência de uma base qualquer elevada a um
//expoente qualquer, ou seja, de NM.
Var
// Seção de Declarações das variáveis 
bas, pote: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Escreva um número para a base: ")
leia (bas)

escreval ("Escreva um número para o expoente: ")
leia (pote)

escreval (bas, " elevado a", pote, " é igual a: ", bas ^ pote)
Fimalgoritmo