Algoritmo "semnome"
//Desenvolver um programa que leia um número e informe
//se ele é positivo, negativo ou nulo.

Var

   num: inteiro




Inicio
   escreval("Informe um número:")
   leia(num)

   se (num < 0) entao
      escreval ("Este é um número negativo.")
   senao

      se(num = 0)entao
         escreval ("Este é um número nulo.")




      senao(num > 0)
         escreval ("Este é um número positivo.")
      fimse
fimse






Fimalgoritmo