Algoritmo "semnome"
// Fazer um programa que pergunte o valor da base e da altura de um retângulo
//e apresente como resposta o valor do perímetro do retângulo.
//P = 2 * (B + H)


Var
bas,alt,per: inteiro



Inicio

escreval("Insira o valor da base do retângulo:")
leia(bas)
escreval("Agora, insira o valor da altura desse retângulo:")
leia(alt)

per <- (alt + bas) * 2


escreval("O perímetro desse retângulo é igual a ",per," .")





Fimalgoritmo