Algoritmo "semnome"

//Desenvolver um programa que apresente o valor de
//uma potência de uma base qualquer elevada a um expoente
//qualquer, ou seja, de BE



Var

   a, b: inteiro





Inicio

   para a de 1 ate 10 passo 1 faca
   
      para b de 1 ate 10 passo 1 faca
        se ( a < 10) entao
         escreva ( " ",a," -" ,b, " " )
         senao
         escreva (a," -" ,b, " " )
         fimse
         
      fimpara // do b
      escreva ()
   fimpara   // do a








Fimalgoritmo